### ISSUE TITLE
Deregistering of Dependencies from Dependencygraph

### ISSUE THREAD

**Issue by wpmp** [monto-editor/broker#2]
To provide correctly working dynamic registration and deregistration of services with the broker, a deregister function in the dependencygraph is required.
Could you please have a look and add such a function?

Best Regards
Wulf

**Comment by seba--** [comment]
It is not clear what feature you require. Can you provide further details and a minimal example that explains the desired behavior?

**Comment by wpmp** [comment]
The dependencygraph registers services by their product/language combination and their dependencies.
Therefore it provides a function named "register", which is called when a new service registers itself to the broker.
When a registered service now deregisters itself, the service and its dependencies will remain in the dependencygraph due to the lack of a "deregister" function which should be capable of removing it from the graph.
I hope this clarifies the problem.

**Comment by seba--** [comment]
@svenkeidel Can you take a look at this issue?

**Comment by svenkeidel** [comment]
I'm on it.
