### ISSUE TITLE
Use ServiceIDs instead of (Product,Language) in the dependency graph.

### ISSUE THREAD

**Issue by svenkeidel** [monto-editor/broker#6]
Hi,

We talked about switching from `(Product,Language)` tuples to `ServiceID`s in the service dependency graph. I would like to assign this task to myself. @wpmp I think you can work on product dependencies and then we can merge our work. We should definitely work on different branches that we don't break each others code. @wpmp, please commit often s.t. I can comment and help you asap.

Best,
Sven

**Comment by wpmp** [comment]
Hi,

did you mean file dependencies? I am a bit confused now.
I will commit some code soon in a new branch.

Wulf

**Comment by svenkeidel** [comment]
No, we wanted to change the service dependencies to graph to use `ServiceID`s instead of `(Product,Language)`. For file dependencies we figured out the type in the last meeting together.

I just wanted to communicate what I will do next, s.t. we can coordinate our work better. I'm sorry if that confused you.

**Comment by svenkeidel** [comment]
I started the work in the branch `service-ids`: fc7c3929189631d9b8161a108ff3364c043cb562

@wpmp, It should now be easier to integrate your work into the existing broker. Let me know if you have difficulties or questions.

Best,
Sven

**Comment by svenkeidel** [comment]
@wpmp, I got the tests working again in c32f106dbf83db1ea95869d42fb921112696232e.

**Comment by svenkeidel** [comment]
Works in HEAD
